name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ğŸ›ï¸
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code ğŸ›ï¸ğŸ›ï¸
      uses: actions/checkout@v2
    
    - name: Install Node.js ğŸ”§
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install NPM packages ğŸ”§ğŸ”§
      run: npm install
    
    - name: Build project ğŸ”§ğŸ”§ğŸ”§
      run: npm run build
    
    # - name: Run tests
    #   run: npm run test

    - name: Upload production-ready build files ğŸ”§ğŸ”§ğŸ”§ğŸ”§
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy ğŸš€
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact ğŸš€ğŸš€
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages ğŸš€ğŸš€ğŸš€
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
